# Site Settings
title: "Yifu Guo | AI Researcher"
name: "Yifu Guo"
description: "Personal Website"
url: https://euyis1019.github.io
baseurl: ""
future: true

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Dockerfile
  - .git
  - .gitignore
